# Generated by Django 2.0.12 on 2019-08-07 07:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('list_pic', models.ImageField(blank=True, null=True, upload_to='article/%Y%m%d')),
                ('content', models.TextField()),
                ('click_nums', models.IntegerField(default=0, verbose_name='阅读数量')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否删除')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ('-add_time',),
            },
        ),
        migrations.CreateModel(
            name='Article_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(verbose_name='评论')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
                ('url', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '文章评论',
                'verbose_name_plural': '文章评论',
                'ordering': ('-add_time',),
            },
        ),
        migrations.CreateModel(
            name='ArticleCommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(verbose_name='回复内容')),
                ('url', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('aomments_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article_Comment', verbose_name='回复id')),
            ],
        ),
        migrations.CreateModel(
            name='Category_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Headlines',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('category', models.CharField(max_length=20, verbose_name='分类')),
                ('conent', models.TextField(default='', verbose_name='内容')),
                ('author_name', models.CharField(max_length=100, verbose_name='来源')),
                ('url', models.URLField(verbose_name='地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'ordering': ('-add_time',),
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('recommends', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
            options={
                'verbose_name': '文章推荐',
                'verbose_name_plural': '文章推荐',
                'ordering': ('-add_time',),
            },
        ),
    ]
